# Generated by Django 2.0.7 on 2018-07-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Currency', '0001_create_currencies_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_from_id', to='Currency.Currency')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_to_id', to='Currency.Currency')),
            ],
            options={
                'db_table': 'currency_pairs',
            },
        ),
    ]
