version: '3.0'

services:
  db:
    image: postgres
  web:
    build: .
    image: carol
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - migration
      - db
  migration:
    image: carol
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
