# Generated by Django 2.0.7 on 2018-07-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyExchangeRate', '0001_create_currency_exchange_rates_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_from_id', to='Currency.Currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_to_id', to='Currency.Currency'),
        ),
    ]
