# Generated by Django 2.0.7 on 2018-07-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyExchangeRate', '0002_alter_currency_exchange_rate_add_foreign_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyexchangerate',
            old_name='date',
            new_name='exchange_date',
        ),
    ]
