# Generated by Django 2.0.7 on 2018-07-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreigncurrencyapp', '0001_create_foreign_currencies_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreigncurrency',
            options={},
        ),
        migrations.RenameField(
            model_name='foreigncurrency',
            old_name='currency',
            new_name='currency_name',
        ),
    ]
